creating numpy arrays 

In [2]:
import numpy as np 
a=np.array([1,2,3])
print(a)


[1 2 3]


In [3]:
# matrix or 2d array
b=np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


CREATING A TENSOR

In [4]:
c=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(c)


[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [5]:
#dtype
np.array([1,2,3],dtype=complex)

array([1.+0.j, 2.+0.j, 3.+0.j])

In [8]:
#np.arange
np.arange(1,11)
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [9]:
np.arange(1,11).reshape(5,2)


array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [12]:
#np.ones and np.zeros
np.ones((3,4))


array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [13]:
np.random.random((3,4))

array([[0.35848816, 0.61944627, 0.22036971, 0.11250223],
       [0.9041202 , 0.7208713 , 0.5083382 , 0.14017587],
       [0.27834213, 0.41445307, 0.35498479, 0.9534163 ]])

In [14]:
#np.linspace
np.linspace(-10,10,10)


array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [15]:
#np.identity
np.identity(4)


array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])